version: '3'

services:
  db:
    container_name: 'db'
    image: postgres:latest
    env_file:
      - .env
    volumes:
    - db_data:/var/lib/postgresql/data
  app:
    build: 
      context: "."
      dockerfile: ".Dockerfile"
    image: "static_app"
    env_file:
      - .env
    ports: 
      - "8080:8080"
    depends_on:
      - db

volumes:
  db_data: